version: "3"
services:
  resenasapp:
    build:
      context: ./resenasapp/
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - resenasapp-api
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
  resenasapp-api:
    build: 
      context: ./resenasservidor/
      dockerfile: Dockerfile
    ports:
    - "4000:4000"
    depends_on:
      - mongo
  mongo:
    image: mongo:4.0.27-xenial
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local

