export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

export const OBTENER_ALBUMES = 'OBTENER_ALBUMES';
export const SIGUIENTE_ALBUM = 'SIGUIENTE_ALBUM';
export const ANTERIOR_ALBUM = 'ANTERIOR_ALBUM';
export const COMENTARIOS_ALBUM_CARGADOS = 'COMENTARIOS_ALBUM_CARGADOS';

export const OBTENER_COMENTARIOS = 'OBTENER_COMENTARIOS';
export const CREAR_COMENTARIO = 'CREAR_COMENTARIO';
export const ACTUALIZAR_COMENTARIO = 'ACTUALIZAR_COMENTARIO';
export const ELIMINAR_COMENTARIO = 'ELIMINAR_COMENTARIO';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';
